services:
  backend-0:
    build: .
    command: sh -c "/wait && /server"
    ports:
      - "5001:5000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    environment:
      - MONGO_USER=root
      - MONGO_PASS=password
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - RABBIT_HOST=rabbitmq
      - WAIT_HOSTS=rabbitmq:15672
      - CONSUMER_NUMBER=0

  backend-1:
    build: .
    command: sh -c "/wait && /server"
    ports:
      - "5002:5000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    environment:
      - MONGO_USER=root
      - MONGO_PASS=password
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - RABBIT_HOST=rabbitmq
      - WAIT_HOSTS=rabbitmq:15672
      - CONSUMER_NUMBER=1

  mongo:
    image: mongo:5.0
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:6-alpine"
    hostname: redis
    ports:
      - "6379:6379"
    command: sh -c "redis-server --appendonly yes"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: "rabbitmq:3.9.1-management"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  redis-data:
  rabbitmq-data: