services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_USER=root
      - MONGO_PASS=password
      - MONGO_HOST=mongo
      - REDIS_HOST=redis

  mongo:
    image: mongo:5.0
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:6-alpine"
    hostname: redis
    ports:
      - "6379:6379"
    command: sh -c "redis-server --appendonly yes"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: