// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package producer

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockPrice is an autogenerated mock type for the Price type
type MockPrice struct {
	mock.Mock
}

// Produce provides a mock function with given fields: ctx, id, price
func (_m *MockPrice) Produce(ctx context.Context, id uuid.UUID, price float64) error {
	ret := _m.Called(ctx, id, price)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64) error); ok {
		r0 = rf(ctx, id, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
