// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package consumer

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockPrice is an autogenerated mock type for the Price type
type MockPrice struct {
	mock.Mock
}

// Consume provides a mock function with given fields: ctx, callbackFunc
func (_m *MockPrice) Consume(ctx context.Context, callbackFunc func(uuid.UUID, float64) error) error {
	ret := _m.Called(ctx, callbackFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(uuid.UUID, float64) error) error); ok {
		r0 = rf(ctx, callbackFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
