// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package consumer

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockPrice is an autogenerated mock type for the Price type
type MockPrice struct {
	mock.Mock
}

// Consume provides a mock function with given fields: ctx, lastID, callbackFunc
func (_m *MockPrice) Consume(ctx context.Context, lastID string, callbackFunc func(uuid.UUID, float64) error) (string, error) {
	ret := _m.Called(ctx, lastID, callbackFunc)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, func(uuid.UUID, float64) error) string); ok {
		r0 = rf(ctx, lastID, callbackFunc)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, func(uuid.UUID, float64) error) error); ok {
		r1 = rf(ctx, lastID, callbackFunc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
